%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
FRASES DEL ENUNCIADO TRADUCIDAS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fe1 = 'jose is dark-skinned and mary is tall'
fe2 = 'jose is studying philosophy, but mary is studying law'
fe3 = 'mary drinks coffee while jose clears the table'
fe4 = 'jose drinks coffee and reads the newspaper'
fe5 = 'jose and hector eat chips and drink beer'
fe6 = 'jose eats chips, but mary prefers paella, although hector drinks coffee and irene reads a novel'
fe7 = 'irene sings and jumps while jose studies'
fe8 = 'hector eats chips and drinks juice while jose sings and skips, although maria reads a novel'
fe9 = 'jose, who is agile, climbs on the climbing wall in the afternoons'
fe10 = 'jose, who is very delicate, eats only red apples'
fe11 = 'the word processor, which is quite a powerful tool, is used to write documents'
fe12 = 'the word processor is a very powerful tool for writing documents, but it is quite slow'
fe13 = 'the mouse that the cat caught was grey'
fe14 = 'the man we saw yesterday was my neighbour'

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
FRASES PARA LA TEMÁTICA DEPORTES
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f1 = 'juan plays football while pedro plays basketball'
f2 = 'javier and juan are the goalkeepers of the team'
f3 = 'rafa has won the roland-garros'
f4 = 'aitana has won the golden ball'
f5 = 'julian is a great player'
f6 = 'miguel is the best basketball player and leo is the best football player'
f7 = 'marta is the best swimmer in her club'
f8 = 'alex plays tennis while marcos plays paddle tennis'
f9 = 'paula has won a gold medal in synchronised swimming'
f10 = 'sara and claudia compete together in rhythmic gymnastics'
f11 = 'daniel is an expert in martial arts and has won several tournaments'
f12 = 'beatriz runs marathons and trains every day'
f13 = 'maria and carlos are the best sports dance couple in the region'
f14 = 'andres plays rugby while diego practices boxing'
f15 = 'lucas has been elected the best player of the tournament'
f16 = 'elena and sofia are the captains of the volleyball team'
f17 = 'tomas has broken the long jump record in his category'
f18 = 'laura practices climbing and has climbed impressive mountains'
f19 = 'javier has been selected for the national handball team'
f20 = 'ana and luis are taking part in an international triathlon competition'
f21 = 'jaime and natalia train together for the next cycling race'
f22 = 'ruben practices archery while ines plays hockey'
f23 = 'clara has been named the best chess player in her school'
f24 = 'alvaro has won the junior tennis championship'
f25 = 'cristina and david are taking part in an international athletics competition'
f26 = 'santiago has beaten his personal record in weightlifting'
f27 = 'jorge and rocio compete in whitewater kayaking'
f28 = 'sofia has achieved a new record in freestyle swimming'
f29 = 'pedro and angela play table tennis on weekends'
f30 = 'diego goes skiing while martina enjoys snowboarding'
f31 = 'lucia has won the title of regional champion in artistic gymnastics'
f32 = 'alberto, who is very agile, practises parkour around the city'
f33 = 'teresa has won a gold medal in shooting'
f34 = 'miguel and sergio enjoy playing badminton after school'
f35 = 'alexis, who is very strong, trains for the wrestling championship'
f36 = 'elisa and pablo are preparing for a relay race'
f37 = 'eduardo practices judo and has obtained his black belt'
f38 = 'ariana, who has great dexterity, plays volleyball on the beach'
f39 = 'andrea has participated in her first triathlon and has managed to finish on the podium'
f40 = 'oscar trains daily to improve his pole vaulting technique'

